#!/bin/bash
printf 'PROJECT Variables\n'
printf '__________________________________\n'
printf 'PROJECT_PATH= \t'$PROJECT_PATH'\n'
printf '\n'
printf '\n'
printf '\n'
printf 'BUILD Variables\n'
printf '__________________________________\n'
printf 'BUILD_DIR= \t'$BUILD_DIR'\n'
printf 'BUILD_PATH= \t'$BUILD_PATH'\n'
printf 'BUILD_TARGET= \t'$BUILD_TARGET'\n'
printf '\n'
printf '\n'
printf '\n'
printf 'CODE Variables\n'
printf '__________________________________\n'
printf 'CODE_PATH= \t'$CODE_PATH'\n'
printf '\n'
printf '\n'
printf '\n'
printf 'TEST Variables\n'
printf '__________________________________'
printf 'TESTS_DIR= \t'$TESTS_DIR'\n'
printf 'TESTS_PATH= \t'$TESTS_PATH'\n'
printf '\n'
printf '\n'
printf '\n'
printf 'SCRIPT Variables\n'
printf '__________________________________'
printf 'SCRIPT_DIR= \t'$SCRIPT_DIR'\n'
printf 'SCRIPT_PATH= \t'$SCRIPT_PATH'\n'
printf '\n'
printf '\n'
printf '\n'
printf 'SVN Variables\n'
printf '__________________________________'
printf 'SVN_IP= \t'$SVN_IP'\n'
printf 'SVN_PATH= \t'$SVN_PATH'\n'
printf 'SVN_PATH_TRUNK= \t'$SVN_PATH_TRUNK'\n'